defaults:
  - /task/model_config@simulator.params.model_config: rope_f1
name: "light_tunnel"
num_samples: 50000
rescale: "none" # rescale handled in simulator 
generation: "independent"
num_cal: [10,50,200,1000]
max_cal: 10000
naugment: 1

simulator:
  name: "light_tunnel"
  params:
    theta_dim: 4
    obs_dim: [3,64,64]
    data_path: "data/light_tunnel"
    exp_name: "uniform_ap_1.8_iso_500.0_ss_0.005"


hidden_dims_x: [32, 64, 128, 128, 64, 32]
hidden_dims_theta: [32, 64, 128, 256, 256, 128, 64, 32]
### METHODS ###
fm_post_transform:
  config:
    npe: "npe"
    flow_x:
      space: "data"
      conditional: True
      probability_path: "ot2"
      prior: 'uniform'
      base_dist: 'data_eps'
      params:
        probability_path_params: {"sigma_min": 1e-4}
        # prior_params: {"rate": 2.0}
        base_dist_params: {"eps": 5e-2}
        # base_dist_params: {}
        drift:
          # architecture: 'resmlp'
          architecture: "cfnet"
          posterior_kwargs:
            input_dim: ${task.simulator.params.obs_dim}
            dropout: 0.0
            batch_norm: True
            context_dim: 10
            theta_with_glu: True
            context_with_glu: False
            activation: "gelu"
            hidden_dims: ${task.hidden_dims_x}
          theta_embedding_kwargs:
            name: "conv2d"
            time_emdedding: True
            output_dim: 10 # same as context_dim
            image_size: ${task.simulator.params.obs_dim}
            n_freqs: 3
          embedding_kwargs:
            name: "conv2d"
            output_dim: 10 # same as context_dim
            image_size: ${task.simulator.params.obs_dim}
    flow_theta:
      space: "data"
      conditional: True
      probability_path: "ot2"
      prior: 'uniform'
      base_dist: 'gaussian'
      params:
        probability_path_params: {"sigma_min": 1e-4}
        # prior_params: {"rate": 2.0}
        base_dist_params: {}
        drift:
          # architecture: 'resmlp'
          architecture: "cfnet"
          posterior_kwargs:
            input_dim: ${task.simulator.params.theta_dim}
            dropout: 0.0
            batch_norm: False
            context_dim: 10
            theta_with_glu: True
            context_with_glu: False
            activation: "gelu"
            hidden_dims: ${task.hidden_dims_theta}
          embedding_kwargs:
            name: "conv2d"
            output_dim: 10 # same as context_dim
            image_size: ${task.simulator.params.obs_dim}
  training_params:
    rescale: ${task.rescale}
    lr: 1e-3
    epochs: 500
    batch_size: 16
    max_patience: 10
    train_size: 0.8
### BASELINES ####

npe:
  training:
    lr: 1e-4
    batch_size: 256
    epochs: 2000
    train_size: 0.8
    max_patience: 20
    rescale: ${task.rescale}
  params:
    embedding_net:
      model_path: 'models'
      load: False
      save: 'last_'
      output_dim: 20
      image_size: ${task.simulator.params.obs_dim}
    npe_params:
      embedding_dim: 10
      ntransform: 1

fmpe:
  config:
    space: "data"
    conditional: True
    probability_path: "ot2"
    prior: 'uniform'
    base_dist: 'gaussian'
    params:
      probability_path_params: {"sigma_min": 1e-4}
      # prior_params: {"rate": 2.0}
      base_dist_params: {}
      drift:
        # architecture: 'resmlp'
        architecture: "cfnet"
        posterior_kwargs:
          input_dim: ${task.simulator.params.theta_dim}
          dropout: 0.0
          batch_norm: False
          context_dim: 20
          theta_with_glu: True
          context_with_glu: False
          activation: "gelu"
          hidden_dims: [32, 64, 128, 256, 512,256, 128, 64, 32]
        embedding_kwargs:
          name: "conv2d"
          output_dim: 20 # same as context_dim
          image_size: ${task.simulator.params.obs_dim}
  training_params:
    rescale: ${task.rescale}
    lr: 1e-3
    epochs: 500
    batch_size: 100
    max_patience: 10
    train_size: 0.8
